apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-mult
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ftp-mult
  template:
    metadata:
      labels:
        app: ftp-mult
    spec:
      containers:
        - name: ftp-mult
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 2121
