apiVersion: v1
kind: Service
metadata:
  name: ftp-mult
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2121
      protocol: TCP
      name: sftp
  selector:
    app: ftp-mult
